String.toLocaleString({
  it: {
    "%game-intro": "",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation":
      '<strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>',
    "%disclaimer":
      '<strong class="important">Note:</strong> This site <a href="https://doodlecricket.github.io/">doodlecricket.github.io</a> is a spin-off of the official version of 2048',
    "%credits": "Baseball Teams images by the internet",
    "%tweet1": 'I scored "',
    "%tweet2": " at 2048-BASEBALL-TEAMS #2048game",
    "%tile-legend": '<strong class="important">Tile Legend:</strong>',
    "%2": "New York Yankees",
    "%4": "St. Louis Cardinals",
    "%8": "Sir Garry Sobers (West Indies)",
    "%16": "Boston Red Sox",
    "%32": "San Francisco Giants",
    "%64": "Los Angeles Dodgers",
    "%128": "Cincinnati Reds",
    "%256": "Pittsburgh Pirates",
    "%512": "Atlanta Braves",
    "%1024": "Detroit Tigers",
    "%2048": "Chicago Cubs",
    "%4096": "Baltimore Orioles",
    "%8192": "Commissioner's Trophy",
    "%p2": "New York Yankees",
    "%p4": "St. Louis Cardinals",
    "%p8": "Sir Garry Sobers (West Indies)",
    "%p16": "Boston Red Sox",
    "%p32": "San Francisco Giants",
    "%p64": "Los Angeles Dodgers",
    "%p128": "Cincinnati Reds",
    "%p256": "Pittsburgh Pirates",
    "%p512": "Atlanta Braves",
    "%p1024": "Detroit Tigers",
    "%p2048": "Chicago Cubs",
    "%p4096": "Baltimore Orioles",
    "%p8192": "Commissioner's Trophy",
  },

  en: {
    "%game-intro": "",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation":
      '<strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>',
    "%disclaimer":
      '<strong class="important">Note:</strong> This site <a href="https://doodlecricket.github.io/">doodlecricket.github.io</a> is a spin-off of the official version of 2048',
    "%credits": "Baseball Teams images by the internet",
    "%tweet1": 'I scored "',
    "%tweet2": " at 2048-BASEBALL-PLAYERS #2048game",
    "%tile-legend": '<strong class="important">Tile Legend:</strong>',
    "%2": "New York Yankees",
    "%4": "St. Louis Cardinals",
    "%8": "Sir Garry Sobers (West Indies)",
    "%16": "Boston Red Sox",
    "%32": "San Francisco Giants",
    "%64": "Los Angeles Dodgers",
    "%128": "Cincinnati Reds",
    "%256": "Pittsburgh Pirates",
    "%512": "Atlanta Braves",
    "%1024": "Detroit Tigers",
    "%2048": "Chicago Cubs",
    "%4096": "Baltimore Orioles",
    "%8192": "Commissioner's Trophy",
    "%p2": "New York Yankees",
    "%p4": "St. Louis Cardinals",
    "%p8": "Sir Garry Sobers (West Indies)",
    "%p16": "Boston Red Sox",
    "%p32": "San Francisco Giants",
    "%p64": "Los Angeles Dodgers",
    "%p128": "Cincinnati Reds",
    "%p256": "Pittsburgh Pirates",
    "%p512": "Atlanta Braves",
    "%p1024": "Detroit Tigers",
    "%p2048": "Chicago Cubs",
    "%p4096": "Baltimore Orioles",
    "%p8192": "Commissioner's Trophy",
  },
});
