String.toLocaleString({
  it: {
    "%game-intro": "",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation":
      '<strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>',
    "%disclaimer":
      '<strong class="important">Note:</strong> This site <a href="https://doodlecricket.github.io/">doodlecricket.github.io</a> is a spin-off of the official version of <a href="http://git.io/2048">2048</a> created by <a href="http://gabrielecirulli.com" target="_blank">Gabriele Cirulli</a>.',
    "%credits":
      'Cricket Players images by <a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>.',
    "%tweet1": 'I scored "',
    "%tweet2": " at 2048-CRICKET-PLAYERS #2048game",
    "%tile-legend": '<strong class="important">Tile Legend:</strong>',
    "%2": "Sir Don Bradman (Australia)",
    "%4": "Sachin Tendulkar (India)",
    "%8": "Sir Garry Sobers (West Indies)",
    "%16": "Sir Jack Hobbs (England)",
    "%32": "Sir Viv Richards (West Indies)",
    "%64": "Steve Smith (Australia)",
    "%128": "Jacques Kallis (South Africa)",
    "%256": "Kumar Sangakkara (Sri Lanka)",
    "%512": "Ricky Ponting (Australia)",
    "%1024": "Shane Warne (Australia)",
    "%2048": "Virat Kohli (India)",
    "%4096": "Joe Root (England)",
    "%8192": "Kane Williamson (New Zealand)",
    "%p0": "Sir Don Bradman (Australia)",
    "%p4": "Sachin Tendulkar (India)",
    "%p8": "Sir Garry Sobers (West Indies)",
    "%p16": "Sir Jack Hobbs (England)",
    "%p32": "Sir Viv Richards (West Indies)",
    "%p64": "Steve Smith (Australia)",
    "%p128": "Jacques Kallis (South Africa)",
    "%p256": "Kumar Sangakkara (Sri Lanka)",
    "%p512": "Ricky Ponting (Australia)",
    "%p1024": "Shane Warne (Australia)",
    "%p2048": "Virat Kohli (India)",
    "%p4096": "Joe Root (England)",
    "%p8192": "Kane Williamson (New Zealand)",
  },

  en: {
    "%game-intro": "",
    "%restart-button": "Play Again",
    "%keep-playing-button": "Keep going",
    "%retry-button": "Retry",
    "%game-won": "You win!",
    "%game-over": "Game over!",
    "%game-explanation":
      '<strong class="important">How to play:</strong> Use your <strong>arrow keys</strong> to move the tiles. When two tiles with the same symbol touch, they <strong>get promoted!</strong>',
    "%disclaimer":
      '<strong class="important">Note:</strong> This site <a href="https://doodlecricket.github.io/">doodlecricket.github.io</a> is a spin-off of the official version of <a href="http://git.io/2048">2048</a> created by <a href="http://gabrielecirulli.com" target="_blank">Gabriele Cirulli</a>.',
    "%credits":
      'Cricket Players images by <a href="http://www.georgetowncupcake.com/" title="Georgetown Cupcake | DC Cupcakes | About">Georgetown Cupcake</a>.',
    "%tweet1": 'I scored "',
    "%tweet2": " at 2048-CRICKET-PLAYERS #2048game",
    "%tile-legend": '<strong class="important">Tile Legend:</strong>',
    "%2": "Sir Don Bradman (Australia)",
    "%4": "Sachin Tendulkar (India)",
    "%8": "Sir Garry Sobers (West Indies)",
    "%16": "Sir Jack Hobbs (England)",
    "%32": "Sir Viv Richards (West Indies)",
    "%64": "Steve Smith (Australia)",
    "%128": "Jacques Kallis (South Africa)",
    "%256": "Kumar Sangakkara (Sri Lanka)",
    "%512": "Ricky Ponting (Australia)",
    "%1024": "Shane Warne (Australia)",
    "%2048": "Virat Kohli (India)",
    "%4096": "Joe Root (England)",
    "%8192": "Kane Williamson (New Zealand)",
    "%p0": "Sir Don Bradman (Australia)",
    "%p4": "Sachin Tendulkar (India)",
    "%p8": "Sir Garry Sobers (West Indies)",
    "%p16": "Sir Jack Hobbs (England)",
    "%p32": "Sir Viv Richards (West Indies)",
    "%p64": "Steve Smith (Australia)",
    "%p128": "Jacques Kallis (South Africa)",
    "%p256": "Kumar Sangakkara (Sri Lanka)",
    "%p512": "Ricky Ponting (Australia)",
    "%p1024": "Shane Warne (Australia)",
    "%p2048": "Virat Kohli (India)",
    "%p4096": "Joe Root (England)",
    "%p8192": "Kane Williamson (New Zealand)",
  },
});
